# Development specifikus beállítások
services:
  app-server:
    ports:
      - "8888:80"
    # Bind mount a fejlesztéshez (live reload)
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=development
      - DEBUG_MODE=true
    env_file:
      - .env.dev

  database:
    # A host gépről is elérhető legyen (pl. MySQL Workbench-hez)
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecodrive
      MYSQL_USER: ecodrive
      MYSQL_PASSWORD: ecodrive2026
    # SQL script futtatása első induláskor
    volumes:
      - ./app/database/database.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    ports:
      - "8080:80"
